# 1번 문제

예상 출력결과: 

139771300307664 (주소 값은 환경마다 다르기 때문에 값이 같지 않아도 됩니다.)

In [ ]:
# apple 변수의 주소 값을 출력해보기 (hint: id()를 사용해보기)
apple = "사과"
print()

140003620333872


# 2번 문제
예상 출력결과:

3

1

6

2.0


In [ ]:
number_1, number_2, number_3, number_4 = 1, 2, 3, 4

# number_1와 number_2 더하기 결과 출력하기
print()

# number_4에서 number_3 빼기 결과 출력하기
print()

# number_2와 number_3 곱하기 결과 출력하기
print()

# number_4를 number_2로 나누기 결과 출력하기
print() 

3
1
6
2.0


# 3번 문제
예상 출력결과:

Life

python


In [ ]:
sentence = "Life is short, you need python"

# 슬라이싱을 통해서 Life만 word_1에 할당하기
word_1 = 
print(word_1)
# 슬라이싱을 통해서 python만 word_2에 할당하기
word_2 = 
print(word_2)



Life
python


# 4번 문제
예상 출력결과:

1234 혹은 46


In [ ]:
'''
다음 아래의 code를 실행하면 아래와 같은 오류가 발생합니다.
TypeError: unsupported operand type(s) for +: 'int' and 'str'
에러가 안생기도록 데이터 타입을 변형해 주세요.
'''

try:
  print(12 + "34")
except Exception as e:
  print("----아래와 같은 에러가 발생했습니다. 데이터 타입 변형을 해주세요.----")
  print(e)

----아래와 같은 에러가 발생했습니다. 데이터 타입 변형을 해주세요.----
unsupported operand type(s) for +: 'int' and 'str'


# 5번 문제
예상 출력결과: 

1 는 홀수입니다.

2 는 짝수입니다.

3 는 홀수입니다.

4 는 짝수입니다.

5 는 홀수입니다.

6 는 짝수입니다.

7 는 홀수입니다.

8 는 짝수입니다.

9 는 홀수입니다.

10 는 짝수입니다.

In [ ]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

for i in x:
  # 조건식 채우기
  if :
    print(i, "는 짝수입니다.")
  else:
    print(i,"는 홀수입니다.")

1 는 홀수입니다.
2 는 짝수입니다.
3 는 홀수입니다.
4 는 짝수입니다.
5 는 홀수입니다.
6 는 짝수입니다.
7 는 홀수입니다.
8 는 짝수입니다.
9 는 홀수입니다.
10 는 짝수입니다.


In [ ]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

index = 0

while index < 10 :
  # 조건식 채우기
  if :
    print(x[index], "는 짝수입니다.")
  else:
    print(x[index], "는 홀수입니다.")
  index += 1

1 는 홀수입니다.
2 는 짝수입니다.
3 는 홀수입니다.
4 는 짝수입니다.
5 는 홀수입니다.
6 는 짝수입니다.
7 는 홀수입니다.
8 는 짝수입니다.
9 는 홀수입니다.
10 는 짝수입니다.


# 6번 문제

두 파라미터의 더하기 값을 return 하는 addition 함수를 완성하세요.

예상 출력결과:
100

In [ ]:
# 매개변수로 받고 더하기 함수를 완성 후, return하기
def addition():
  

  return result

number_1 = 86
number_2 = 14

result = addition(number_1, number_2)
print(result)

100


# 7번 문제

예상출력 결과:
matrix_np 형태:  
(3, 2)

matrix_np의 전치행렬:  
[[1 3 5]

 [2 4 6]]
 
행렬 곱 결과:

[[35 44]

 [44 56]]

result의 대각행렬: 

 [35 56]

In [ ]:
import numpy as np

matrix_np = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

# matrix_np의 형태 출력 해보기
print("matrix_np 형태: ", )

# matrix_np를 전치(transpose) 해보기 (hint: T or transpose())
matrix_tp_np = matrix_np.T
print("matrix_np의 전치행렬: ", )

# matrix_tp_np와 matrix_np를 행렬 곱 해보기 (hint: @, 출력은 2x2 행렬)
result = 
print("행렬 곱 결과:", result)

# result의 결과에서 대각행렬 구하기
print("result의 대각행렬: ", )

matrix_np 형태:  (3, 2)
matrix_np의 전치행렬:  [[1 3 5]
 [2 4 6]]
행렬 곱 결과: [[35 44]
 [44 56]]
result의 대각행렬:  [35 56]


# 8번 문제
예상출력 결과:

1차원 벡터:  [1 2 3 4 5 6]

(2, 3) 형태의 행렬:  
[[1 2 3]

 [4 5 6]]

In [ ]:
import numpy as np

matrix_np = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

# matrix_np를 1차원 벡터로 만들기
print("1차원 벡터: ", )

# matrix_np를 (2, 3) 형태의 행렬로 만들기 (전치행렬은 제외)
print("(2, 3) 형태의 행렬: ", )

1차원 벡터:  [1 2 3 4 5 6]
(2, 3) 형태의 행렬:  [[1 2 3]
 [4 5 6]]
